// Auto-generated by scripts/generate-placeholder-labels.mjs
// Do not edit manually.
export const DOCX_PLACEHOLDER_LABELS = [
  "图片",
  "文本框",
  "图表",
  "图形",
  "组合图形",
  "内容控件",
  "表格",
  "分节符",
  "字段",
  "分页符"
] as const;

export const PDF_PLACEHOLDER_LABELS = [
  "链接",
  "图片",
  "对象",
  "图形"
] as const;
